import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs/promises";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

const includePackages = [
  "fs-extra",
  "pdf-lib",
  "pdf-parse",
  "pdf2pic",
  "pdfjs-dist",
  "text-from-image"
];

const external = [
  "obsidian",
  "electron",
  ...builtins,
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
].filter(pkg => !includePackages.includes(pkg));

const distDir = path.resolve("dist"); 
const workerFile = path.join(distDir, "");
const manifestSrc = path.resolve("manifest.json");

const copyPdfWorker = async () => {
  const src = path.resolve("node_modules/pdfjs-dist/build/pdf.worker.mjs");
  const dest = path.join(workerFile, "pdf.worker.js");

  await fs.mkdir(workerFile, { recursive: true });
  await fs.copyFile(src, dest);
  console.log(`Copied pdf.worker.mjs → dist/pdf.worker.js`);
};

const copyManifest = async () => {
  const dest = path.join(distDir, "manifest.json");
  await fs.copyFile(manifestSrc, dest);
  console.log(`Copied manifest.json → dist/manifest.json`);
};

const build = async () => {
  const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external,
    platform: "browser",
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: path.join(distDir, "main.js"),
    minify: prod,
  });

  if (prod) {
    await context.rebuild();
    await copyPdfWorker();
    await copyManifest();
    console.log("Build complete.");
    process.exit(0);
  } else {
    await context.watch();
    await copyPdfWorker();
    await copyManifest();
    console.log("Watching for changes...");
  }
};

build().catch(err => {
  console.error(err);
  process.exit(1);
});
